CREATE  DATABASE dbHospital
GO
 USE dbHospital
 GO 
  

  CREATE SCHEMA PACIENTE
  GO
   CREATE SCHEMA MEDICO
   GO 
   CREATE SCHEMA HISTORIA
   GO

   CREATE TABLE PACIENTE.PACIENTE 
   ( 
   CODPAC INT NOT NULL IDENTITY (1,1),
   NOMPAC VARCHAR(120) NOT NULL,
   APEPATPAC  VARCHAR(120) NOT NULL,
   APEMATPAC  VARCHAR(120) NOT NULL,
   FECNACPAC DATE NOT NULL,
   SEXPAC CHAR (1) NOT NULL,
   DNIPAC CHAR (8) NOT NULL,
   TELEFPAC VARCHAR(9)  NULL,
   EMAILPAC  VARCHAR(100)  NULL,
   DOMPAC  VARCHAR(120) NOT NULL,
   UBIGEOPAC CHAR (6) NOT NULL,
   FECREGPAC DATETIME  NULL DEFAULT GETDATE () ,
   OBSERVPAC  VARCHAR(250)  NULL,
   CONSTRAINT PK_CODPAC PRIMARY KEY (CODPAC)
   )
   GO

   CREATE TABLE HISTORIA.HISTORIA 
   (
   CODHIST INT NOT NULL IDENTITY (1,1),
   FECHIST DATETIME NOT NULL,
   OBSHIST VARCHAR (1800) NOT NULL,
   CONSTRAINT PK_CODHIST PRIMARY KEY (CODHIST)
   )
   GO
   CREATE TABLE PACIENTE.HISTORIA_PACIENTE
   (
   CODHIST INT NOT NULL,
   CODPAC INT NOT NULL,
   CODMED INT NOT NULL,
   CONSTRAINT PK_CODHIST
   PRIMARY KEY (CODHIST,CODPAC,CODMED)
   )
   GO

   CREATE TABLE HISTORIA.TURNO
   (
   CODTUR INT NOT NULL IDENTITY (1,1),
   FECTUR DATETIME,
   ESTTUR SMALLINT,
   OBSTUR VARCHAR (500),
   CONSTRAINT PK_CODTUR PRIMARY KEY (CODTUR)
   )
   GO

   CREATE TABLE PACIENTE.TURNO_PACIENTE
   (
   CODTUR INT NOT NULL,
   CODPAC INT ,
   CODMED INT,
    CONSTRAINT PK_CODTUR
	PRIMARY KEY  (CODTUR,CODPAC,CODMED)
   )
   GO

  CREATE TABLE PACIENTE.UBIGEO
  (
  CODUB CHAR (6) NOT NULL,
  DISTUB VARCHAR (60),
  PROVUB VARCHAR (60),
  DEPAUB VARCHAR (60)
  CONSTRAINT PK_CODUB PRIMARY KEY (CODUB)
  )
  GO

  CREATE TABLE MEDICO.ESPECIALIDAD
  (
  CODESP INT NOT NULL IDENTITY (1,1),
  NOMESP VARCHAR (80) NOT NULL,
  OBSESP VARCHAR (100)  NULL,
  CONSTRAINT PK_CODESP PRIMARY KEY (CODESP)
  )
  GO

  CREATE TABLE MEDICO.MEDICO 
  (
  CODMED INT NOT NULL IDENTITY (1,1),
  NOMMED VARCHAR (120) NOT NULL,
  APEPATMED VARCHAR (120) NOT NULL,
  APEMATMED VARCHAR (120) NOT NULL,
  FECNACMED DATE NOT NULL,
  SEXMED CHAR (1) NOT NULL,
  DNIMED CHAR (8) NOT NULL,
  TELFMED VARCHAR (9)  NULL,
  EMAILMED VARCHAR (120) NULL,
  DOMMED VARCHAR (120) NOT NULL,
  UBIGEOMED CHAR(6) NOT NULL,
  FECREGMED DATETIME NULL DEFAULT GETDATE (),
  OBSERVMED VARCHAR (180),
  CONSTRAINT PK_CODMED PRIMARY KEY (CODMED)
  )
  GO
  
   CREATE TABLE MEDICO.MEDICO_ESPECIALIDAD
   (
   CODMED INT NOT NULL,
   CODESP INT NOT NULL,
   DESCESP VARCHAR (1000),
   CONSTRAINT PK_COMED 
   PRIMARY KEY (CODMED,CODESP)
   )
   GO

   --- RELACION DE PACIENTE CON UBIGEO 
   ALTER TABLE PACIENTE.PACIENTE 
   ADD CONSTRAINT FK_PACIENTE_UBIGEO FOREIGN KEY (UBIGEOPAC) REFERENCES PACIENTE.UBIGEO (CODUB)
   GO
   --- RELACION DE MEDICO_ESPECIALIDAD CON MEDICO
   ALTER TABLE MEDICO.MEDICO_ESPECIALIDAD 
   ADD CONSTRAINT  FK_MEDICO_ESPECIALIDAD_MEDICO  FOREIGN KEY (CODMED) REFERENCES MEDICO.MEDICO (CODMED)
   GO

  --- RELACION DE MEDICO_ESPECIALIDAD CON ESPECIALIDAD
   ALTER TABLE MEDICO.MEDICO_ESPECIALIDAD 
   ADD CONSTRAINT FK_MEDICO_ESPECIALIDAD_ESPECIALIDAD   FOREIGN KEY (CODESP) REFERENCES MEDICO.ESPECIALIDAD ( CODESP )
   GO

   --- RELACION TURNO PACIENTE CON TURNO 
   ALTER TABLE PACIENTE.TURNO_PACIENTE
   ADD CONSTRAINT FK_TURNO_PACIENTE_TURNO  FOREIGN KEY (CODTUR) REFERENCES HISTORIA.TURNO (CODTUR)
   GO

   --- RELACION DE TURNO PACIENTE CON PACIENTE
     ALTER TABLE PACIENTE.TURNO_PACIENTE
   ADD CONSTRAINT FK_TURNO_PACIENTE_PACIENTE   FOREIGN KEY (CODPAC) REFERENCES PACIENTE.PACIENTE (CODPAC)
   GO

      --- RELACION DE TURNO PACIENTE CON MEDICO
     ALTER TABLE PACIENTE.TURNO_PACIENTE
   ADD CONSTRAINT FK_TURNO_PACIENTE_MEDICO   FOREIGN KEY (CODMED) REFERENCES MEDICO.MEDICO (CODMED)
   GO

 --- RELACION DE HISTORIA_PACIENTE CON PACIENTE
   ALTER TABLE PACIENTE.HISTORIA_PACIENTE
   ADD CONSTRAINT FK_HISTORIA_PACIENTE_PACIENTE  FOREIGN KEY (CODPAC) REFERENCES PACIENTE.PACIENTE (CODPAC)
   GO

  --- RELACION DE HISTORIA_PACIENTE CON MEDICO
   ALTER TABLE PACIENTE.HISTORIA_PACIENTE
   ADD CONSTRAINT FK_HISTORIA_PACIENTE_MEDICO FOREIGN KEY (CODMED) REFERENCES MEDICO.MEDICO (CODMED)
   GO

     --- RELACION DE HISTORIA_PACIENTE CON HISTORIA
   ALTER TABLE PACIENTE.HISTORIA_PACIENTE
   ADD CONSTRAINT FK_HISTORIA_PACIENTE_HISTORIA FOREIGN KEY (CODHIST) REFERENCES HISTORIA.HISTORIA (CODHIST)
   GO

     --- RELACION DE MEDICO CON UBIGEO
   ALTER TABLE MEDICO.MEDICO
   ADD CONSTRAINT FK_MEDICO_UBIGEO FOREIGN KEY (UBIGEOMED) REFERENCES PACIENTE.UBIGEO (CODUB)
   GO
